version: '2.4'
services:
  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5001:5001'
  billing:
    build:
      context: .
      dockerfile: ./apps/billing/Dockerfile
      target: development
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '5002:5002'
    env_file:
      - ./apps/auth/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  board:
    build:
      context: .
      dockerfile: ./apps/board/Dockerfile
      target: development
    command: npm run start:dev board
    ports:
      - '5003:5003'
    env_file:
      - ./apps/board/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  search:
    build:
      context: .
      dockerfile: ./apps/search/Dockerfile
      target: development
    command: npm run start:dev search
    environment:
      - ELASTIC_CLIENT_APIVERSIONING=true
    ports:
      - '5004:5004'
    env_file:
      - ./apps/search/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 30s # 30초마다 검사
      timeout: 10s # 검사 타임아웃 10초
      retries: 5 # 실패 시 최대 5회 재시도
      start_period: 30s # 컨테이너 시작 후 30초 대기 뒤 검사 시작

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: playlist_db2
    ports:
      - '3308:3306'
    volumes:
      - mysql_fresh_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s # 검사 주기
      timeout: 10s # 검사 타임아웃
      retries: 5 # 재시도 횟수
      start_period: 30s # 시작 후 대기 시간

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200' # HTTP API
      - '9300:9300' # Transport
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  mysql_fresh_data:
    driver: local
  esdata:
    driver: local
