import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <header style={{ padding: "1rem", borderBottom: "1px solid #ccc" }}>
            <Navbar />
          </header>
          <main style={{ padding: "1rem" }}>{children}</main>
          <footer style={{ padding: "1rem", borderTop: "1px solid #ccc" }}>
            Footer
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
